import type { Metadata } from 'next';
import { type ReactNode } from 'react';

import '@/styles/global.css';
import '@/styles/variables.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): ReactNode {
  return (
    <html lang="en">
      <body
        style={{
          background: 'var(--color-hermes-100)',
        }}
      >
        {children}
      </body>
    </html>
  );
}
