name: Lighthouse Scan

on:
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse
        run: lighthouse https://www.patrickroelofs.com --output json --output-path ./lighthouse-report.json

      - name: Convert Lighthouse report to Markdown
        run: |
          npm install -g lighthouse-badges
          lighthouse-badges -s ./lighthouse-report.json -o ./lighthouse-report.md

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./lighthouse-report.md

      - name: Post Lighthouse report as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ./lighthouse-report.md
