name: Lighthouse Scan

on:
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.7.x

      - name: Run Lighthouse
        run: lhci autorun --collect.url=https://www.patrickroelofs.com --upload.target=filesystem --upload.outputDir=./

      - name: Convert Lighthouse report to markdown
        run: |
          npm install -g lighthouse-badges
          lighthouse-badges --input=./lhr-*.html --output=./report.md

      - name: Post Lighthouse report as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ./report.md
