name: Lighthouse Scan

on:
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f

      - name: Install Lighthouse and Lighthouse CI
        run: npm install -g lighthouse @lhci/cli

      - name: Run Lighthouse
        run: lighthouse https://www.patrickroelofs.com --output json --output-path ./lighthouse-report.json --chrome-flags="--headless"

      - name: Generate Lighthouse CI report
        run: lhci upload --target=filesystem --outputDir=./lhci-report --reportFilename=lighthouse-report.md

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./lhci-report/lighthouse-report.md

      - name: Post Lighthouse report as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ./lhci-report/lighthouse-report.md
